return {
  ["workshop-1113081094"]={
    configuration_options={
      armormarble=0.7,
      armour_health=1,
      arms_uses=1,
      bedroll_uses=1,
      chester_a=false,
      clean_t=false,
      consume="no",
      fence_second=true,
      heatrock_u=true,
      icebox=0.15,
      krampussack=1,
      no_grassgekko=true,
      pick=true,
      pickaxe_uses=1,
      piggybackspeed=0.9,
      saltbox=0.25,
      siestacanopy=15,
      size=99,
      tent=15,
      wall_armor=0 
    },
    enabled=true 
  },
  ["workshop-1392778117"]={
    configuration_options={
      BackCubChance=0.7,
      BetterCookBook=true,
      BookRecipetabs="bookbuilder",
      CleaningUpStench=false,
      DigestedItemMsg=true,
      DressUp=true,
      FestivalRecipes=false,
      FlowerWeaponsChance=0.03,
      FoliageathChance=0.005,
      HiddenUpdateTimes=56,
      Language="chinese",
      OverripeTime=1,
      PestRisk=0,
      PhoenixBattleDifficulty=2,
      PhoenixRebirthCycle=7200,
      RevolvedUpdateTimes=20,
      SivFeaStrength=3,
      SivingRootTex=1,
      TechUnlock="prototyper",
      Title="" 
    },
    enabled=true 
  },
  ["workshop-1595631294"]={
    configuration_options={
      BundleItems=false,
      ChangeSkin=true,
      Digornot=false,
      DragonflyChest=false,
      Icebox=false,
      SaltBox=false 
    },
    enabled=true 
  },
  ["workshop-1607644339"]={
    configuration_options={ Morecooking=true, Morefeeding=true, Times=1.5 },
    enabled=true 
  },
  ["workshop-1699194522"]={ configuration_options={  }, enabled=true },
  ["workshop-1894295075"]={ configuration_options={  }, enabled=true },
  ["workshop-1909182187"]={
    configuration_options={
      ["UI相关"]=false,
      containerdrag_setting=2,
      difficulty_switch=true,
      language_switch="ch",
      medal_goodmax_resources_multiple=0,
      medal_goodmid_resources_multiple=1,
      medal_inv_switch=true,
      medal_shardskinholes_switch=true,
      medal_tech_lock=false,
      medal_tips_switch=true,
      medalequipslots_switch=true,
      medalpage_switch=true,
      show_medal_fx=true,
      transplant_switch=true,
      ["世界设置"]=false,
      ["信息展示"]=false,
      ["其他模组相关"]=false,
      ["基础设置"]=false 
    },
    enabled=true 
  },
  ["workshop-1991746508"]={ configuration_options={ Language="A", ShowBuff=true }, enabled=true },
  ["workshop-1998081438"]={ configuration_options={ StackMode=true, StackRadius=10 }, enabled=true },
  ["workshop-2078243581"]={
    configuration_options={ Blue=0, Display="target", Green=0, Projectile=true, Red=1, Type="hit" },
    enabled=true 
  },
  ["workshop-2119742489"]={
    configuration_options={ Hunger_Cost=1, Ownership=false, Sanity_Cost=1 },
    enabled=true 
  },
  ["workshop-2287303119"]={
    configuration_options={
      [""]=0,
      T_crop=true,
      chestB=-1,
      chestG=-1,
      chestR=-1,
      display_hp=1,
      food_estimation=-1,
      food_order=0,
      food_style=0,
      item_info_mod=0,
      lang="Auto",
      show_buddle_item=1,
      show_food_units=-1,
      show_uses=-1 
    },
    enabled=true 
  },
  ["workshop-2572244884"]={ configuration_options={  }, enabled=true },
  ["workshop-2577742416"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  },
  ["workshop-2683018309"]={ configuration_options={  }, enabled=true },
  ["workshop-2753774601"]={
    configuration_options={
      [""]=0,
      button_can_be_moved=true,
      rb_cd=false,
      rb_penalty=false,
      rb_switch=true,
      tb_consume=false,
      tb_switch=true 
    },
    enabled=true 
  },
  ["workshop-2771698903"]={
    configuration_options={
      MOD_RESTART_ALLOW_KILL=true,
      MOD_RESTART_ALLOW_RESTART=true,
      MOD_RESTART_ALLOW_RESURRECT=true,
      MOD_RESTART_CD_BONUS=0,
      MOD_RESTART_CD_KILL=1,
      MOD_RESTART_CD_MAX=0,
      MOD_RESTART_CD_RESTART=2,
      MOD_RESTART_CD_RESURRECT=1,
      MOD_RESTART_FORCE_DROP_MODE=0,
      MOD_RESTART_IGNORING_ADMIN=true,
      MOD_RESTART_MAP_SAVE=1,
      MOD_RESTART_RESURRECT_HEALTH=0,
      MOD_RESTART_TRIGGER_MODE=1,
      MOD_RESTART_WELCOME_TIPS=true,
      MOD_RESTART_WELCOME_TIPS_TIME=10 
    },
    enabled=true 
  },
  ["workshop-2798599672"]={
    configuration_options={
      config_render=true,
      slot_amulet="extrabody3",
      slot_armor="extrabody1",
      slot_clothing="extrabody2" 
    },
    enabled=true 
  },
  ["workshop-2823458540"]={ configuration_options={ language="zhs" }, enabled=true },
  ["workshop-2831731559"]={ configuration_options={ DEPLOY_RULE=true }, enabled=true },
  ["workshop-2928810007"]={
    configuration_options={
      zx_beebox=true,
      zx_granary_difficult=0,
      zx_granary_freshrate=0.2,
      zx_items_language="ch",
      zx_meatrack=true,
      ["其他物品"]=false,
      ["基础设置"]=false,
      ["粮仓设置"]=false 
    },
    enabled=true 
  },
  ["workshop-363112314"]={ configuration_options={  }, enabled=true },
  ["workshop-375859599"]={
    configuration_options={
      divider=5,
      random_health_value=0,
      random_range=0,
      send_unknwon_prefabs=false,
      show_type=0,
      unknwon_prefabs=1,
      use_blacklist=true 
    },
    enabled=true 
  },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  },
  ["workshop-661253977"]={
    configuration_options={ amudiao=true, baodiao=1, kong=0, nillots=0, rendiao=2, zbdiao=true },
    enabled=true 
  } 
}